modLoader = "javafml" #mandatory

loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "gnu v3"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "applecrates" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "Apple Crates" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile = "logo.png" #optional

credits = "MMD for helping out, Geegor for extensively bugtesting the pre-release" #optional

authors = "Absolem Jackdaw" #optional

description = '''
Sell your stuff in fancy crates!
'''

[[dependencies.applecrates]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.applecrates]]
modId = "applecrates_byg"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_bop"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_botania"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_intdyn"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_premwood"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_solarforge"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_fruit"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_malum"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_nourished"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.applecrates]]
modId = "applecrates_tcon"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"