modLoader = "javafml" #mandatory

loaderVersion = "${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "${license}"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile = "logo.png" #optional

credits = "MMD for helping out, Geegor for extensively bugtesting the pre-release" #optional

authors = "Absolem Jackdaw" #optional

description = '''${description}'''

[[dependencies.${mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[${forge_version},)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
#[[dependencies.applecrates]]
#modId = "sectionprotection"
#mandatory = false
#versionRange = "[0.8.0,)"
#ordering = "NONE"
#side = "SERVER"

[[dependencies.${mod_id}]]
modId = "applecrates_byg"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_bop"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_botania"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_intdyn"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_premwood"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_solarforge"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_fruit"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_malum"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_nourished"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "applecrates_tcon"
mandatory = false
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"