# Project
version=9.0.4
group=absolemjackdaw
java_version=21
releasetype=release
changelog=add connected function to stack applecrates. alter datagen to generate connected crates.

# Common
minecraft_version=1.21.11
parchment_minecraft=1.21.10
parchment_version=2025.10.12
neo_form_version=1.21.11-20251209.172050

# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.140.2+1.21.11
fabric_loader_version=0.18.4

# Mod options
mod_name=Apple Crates
mod_author=Absolem Jackdaw
mod_id=applecrates
license=MIT
credits=MMD for helping out, Geegor for extensively bugtesting the pre-release
minecraft_version_range=[1.21.10, 1.22)
description=Sell your stuff in fancy crates

# publishing
modrinth_project=oQaAgvJv
cf_project=630726

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
