# Project
version=3.0.2
group=absolemjackdaw
java_version=17
releasetype=beta
changelog=backup your saves before using this version |> fix items in crate not rendering

# Common
minecraft_version=1.20.1
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)
//forge_ats_enabled=true

# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.9

# Mod options
mod_name=Apple Crates
mod_author=Absolem Jackdaw
mod_id=applecrates
license=gnu v3
credits=MMD for helping out, Geegor for extensively bugtesting the pre-release
minecraft_version_range=[1.20.1, 1.22)
description=Sell your stuff in fancy crates

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
