modLoader = "javafml" #mandatory

loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "gnu v3"

issueTrackerURL = "https://github.com/ArtixAllMighty/AppleCrates/issues" #optional

[[mods]] #mandatory

modId = "applecrates_intdyn" #mandatory

version = "${file.jarVersion}" #mandatory

displayName = "Apple Crates for Integrated Dynamics" #mandatory

displayURL = "https://www.curseforge.com/minecraft/mc-mods/apple-crates" #optional

logoFile = "../../../../../Common/src/main/resources/icon.png" #optional

authors = "Absolem Jackdaw" #optional

description = '''
Sell your stuff in fancy crates! support for Integrated Dynamics
'''

[[dependencies.applecrates_intdyn]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.applecrates_intdyn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.applecrates_intdyn]]
modId = "applecrates"
mandatory = true
versionRange = "[0.8.0,)"
ordering = "NONE"
side = "SERVER"