plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'net.darkhax.curseforgegradle' version '1.0.11'
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}

jar {
    finalizedBy('reobfJar')
}

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn(tasks.build)
    apiToken = findProperty('cf_api_token')
    def mainFile = upload(630726, file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"))
    mainFile.displayName = "${mod_name}-forge-${minecraft_version}-${version}"
    mainFile.releaseType = "${releasetype}"
    mainFile.changelog = "${changelog}"
    mainFile.changelogType = 'markdown'
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addJavaVersion('Java 17')
    mainFile.addModLoader('neoforge')
    mainFile.addModLoader('forge')
    mainFile.addOptional('sectionprotection')
    mainFile.addOptional('byg-crates')
    mainFile.addOptional('plenty-crates')
    mainFile.addOptional('dynamic-crates')
    mainFile.addOptional('botanical-crates')
    mainFile.addOptional('malumian-crates')
    mainFile.addOptional('premium-crates')
    mainFile.addOptional('fruit-crates')
    mainFile.addOptional('enlightened-crates')
    mainFile.addOptional('solar-crates')
    mainFile.addOptional('construct-crates')
    mainFile.addOptional('forbidden-crates')
    mainFile.addOptional('firma-crates')
}
